##* Hello world
GET http://localhost:3333

@base_url = http://localhost:3333

###! Create Partner
POST {{base_url}}/partners
Content-Type: application/json

{
  "name": "Partner name"
}

###* List Partners
GET {{base_url}}/partners

@partner_id = c22e4874-2670-46a5-b14b-8f6bc95554df

###! Create Customer
POST {{base_url}}/customers
Content-Type: application/json

{
  "name": "Customer name",
  "cpf": "035209851-10"
}

###* List Customers
GET {{base_url}}/customers

@customer_id = 6b6513f5-69cc-4393-9476-fbce518349de

###! Create Event
POST {{base_url}}/events
Content-Type: application/json

{
  "name": "event name",
  "description": "event description",
  "date": "2020-01-01T00:00:00.000Z",
  "partner_id": "{{partner_id}}"
}

###* List Events
GET {{base_url}}/events

@event_id = a04c9551-3e8d-43ce-84aa-e9a81dabab6c

###! Create Event Section
POST {{base_url}}/events/{{event_id}}/sections
Content-Type: application/json

{
  "name": "event section name",
  "description": "event section description",
  "total_spots": 1,
  "price": 100.00
}

@section_id = d0df15b5-533d-4050-b21f-ddc8f031a5fc

@spot_id = 8c30612f-d9f8-4fbd-9f10-62d569bb9e6f

###* List sections of event
GET {{base_url}}/events/{{event_id}}/sections

###? Update section of event
PUT {{base_url}}/events/{{event_id}}/sections/{{section_id}}
Content-Type: application/json

{
  "name": "updated section name",
  "description": "updated section description"
}

###* List spots of section
GET {{base_url}}/events/{{event_id}}/sections/{{section_id}}/spots HTTP/1.1

###? Update spot location
PUT {{base_url}}/events/{{event_id}}/sections/{{section_id}}/spots/{{spot_id}} HTTP/1.1
Content-Type: application/json

{
  "location": "spot location"
}
